name: CMake Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y devscripts debhelper rpm

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Create build directory
        run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install

      - name: Build
        run: cmake --build _build

      - name: Install
        run: cmake --build _build --target install

      - name: Run tests
        run: ctest --test-dir _build --output-on-failure

      - name: Create packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd _build
          cpack -G DEB
          cpack -G RPM
          cpack -G TGZ

      - name: Create source archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          tar -czf solver-${VERSION}.tar.gz .
          zip -r solver-${VERSION}.zip .

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: packages-ubuntu
          path: |
            _build/*.deb
            _build/*.rpm
            _build/*.tar.gz
            solver-*.tar.gz
            solver-*.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _build/*.deb
            _build/*.rpm
            _build/*.tar.gz
            solver-*.tar.gz
            solver-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
